# Generated by Django 5.1.5 on 2025-01-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, default='0000000000', max_length=15, null=True)),
                ('route', models.CharField(choices=[('dd_nagar', 'DD Nagar'), ('morar', 'Morar'), ('lashkar', 'Lashkar'), ('dabra', 'Dabra')], max_length=20)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_app.bus')),
                ('assigned_seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bus_app.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='bus_app.student'),
        ),
    ]
