# Generated by Django 5.1.5 on 2025-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.CharField(choices=[('ddnagar', 'DD Nagar'), ('morar', 'Morar'), ('lashkar', 'Lashkar'), ('dabra', 'Dabra')], max_length=20),
        ),
    ]
