# Generated by Django 5.1.5 on 2025-02-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0002_alter_student_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='school',
        ),
    ]
