# Generated by Django 5.1.5 on 2025-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_rename_course_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.CharField(default='@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
