# Generated by Django 5.1.5 on 2025-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.CharField(choices=[('ddnagar', 'DD Nagar'), ('morar', 'Morar'), ('lashkar', 'Lashkar'), ('dabra', 'Dabra'), ('anand nagar', 'Anand Nagar'), ('sai baba', 'Sai Baba'), ('bada', 'Bada'), ('hazira', 'Hazira')], max_length=20),
        ),
    ]
