# Generated by Django 5.1.5 on 2025-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0006_alter_student_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
