# Generated by Django 5.1.5 on 2025-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0007_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
