# Generated by Django 5.1.5 on 2025-02-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0008_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SOET', 'SOET'), ('SOAG', 'SOAG'), ('SOM', 'SOM'), ('SOS', 'SOS'), ('SOAD', 'SOAD'), ('SOP', 'SOP'), ('SOL', 'SOL'), ('SOJMC', 'SOJMC'), ('SONS', 'SONS'), ('SOE', 'SOE'), ('SOMPS', 'SOMPS')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
