# Generated by Django 5.1.5 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0009_remove_student_email_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15, null=True),
        ),
    ]
