# Generated by Django 5.1.5 on 2025-02-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0010_alter_student_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='identifier_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='crm_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='bus_app.bus')),
            ],
        ),
    ]
