# Generated by Django 5.1.5 on 2025-02-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0011_stoppage_bus_identifier_number_student_crm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppage',
            name='location',
        ),
    ]
