# Generated by Django 5.1.5 on 2025-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0013_bus_driver_alter_driver_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='stoppages',
            field=models.ManyToManyField(blank=True, related_name='buses', to='bus_app.stoppage'),
        ),
    ]
