# Generated by Django 5.1.5 on 2025-02-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0014_bus_stoppages'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoppage',
            name='bus',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bus_stoppages', to='bus_app.bus'),
            preserve_default=False,
        ),
    ]
