# Generated by Django 5.1.5 on 2025-02-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0015_stoppage_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoppage',
            name='bus',
        ),
    ]
