# Generated by Django 5.1.5 on 2025-02-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0016_remove_stoppage_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_or_crm',
            field=models.CharField(choices=[('roll_number', 'Roll Number'), ('crm_id', 'CRM ID')], default='roll_number', max_length=20),
        ),
    ]
