# Generated by Django 5.1.5 on 2025-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0017_student_gender_student_roll_or_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
