# Generated by Django 5.1.5 on 2025-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0020_school_alter_bus_route_alter_stoppage_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SOET', 'SOET'), ('SOAG', 'SOAG'), ('SOM', 'SOM'), ('SOS', 'SOS'), ('SOAD', 'SOAD'), ('SOP', 'SOP'), ('SOL', 'SOL'), ('SOJMC', 'SOJMC'), ('SONS', 'SONS'), ('SOE', 'SOE'), ('SOMPS', 'SOMPS')], default='SOET', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stoppage',
            name='route',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.CharField(choices=[('ddnagar', 'DD Nagar'), ('morar', 'Morar'), ('lashkar', 'Lashkar'), ('dabra', 'Dabra'), ('anand nagar', 'Anand Nagar'), ('sai baba', 'Sai Baba'), ('bada', 'Bada'), ('hazira', 'Hazira'), ('morena', 'Morena')], default='morar', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
