# Generated by Django 5.1.5 on 2025-02-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0021_alter_student_school_alter_bus_route_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_or_crm',
        ),
    ]
