# Generated by Django 5.1.5 on 2025-02-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0023_program_route_school_remove_driver_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_app.route'),
        ),
    ]
