# Generated by Django 5.1.5 on 2025-02-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0024_alter_student_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.route'),
        ),
    ]
