# Generated by Django 5.1.5 on 2025-02-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0025_alter_stoppage_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='insurance_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='pollution_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='pollution_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='pollution_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='tax_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='tax_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='tax_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_app.route'),
        ),
    ]
