# Generated by Django 5.1.5 on 2025-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0026_bus_insurance_issue_date_bus_insurance_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
    ]
