# Generated by Django 5.1.5 on 2025-02-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0027_remove_bus_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
    ]
