# Generated by Django 5.1.5 on 2025-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0029_allotment_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license_number',
            new_name='D_license_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='reference_by',
            field=models.CharField(default='akash upadhyay', max_length=50),
            preserve_default=False,
        ),
    ]
