# Generated by Django 5.1.5 on 2025-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0030_rename_license_number_driver_d_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Route', 'Route'), ('All', 'All')], default='All', max_length=10),
        ),
    ]
