# Generated by Django 5.1.5 on 2025-02-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0033_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppages', to='bus_app.route'),
        ),
    ]
