# Generated by Django 5.1.5 on 2025-02-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0034_alter_stoppage_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='stoppage',
            name='route',
        ),
        migrations.AlterField(
            model_name='student',
            name='stoppage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='bus',
            name='stoppages',
        ),
        migrations.AddField(
            model_name='route',
            name='stoppages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='programs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='bus_app.bus'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='bus_app.driver'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='bus_app.route'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='bus_app.bus'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='bus_app.route'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus_app.bus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bus_app.bus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='crm_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bus_app.route'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Stoppage',
        ),
    ]
