# Generated by Django 5.1.5 on 2025-02-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0036_remove_route_stoppages_remove_school_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_app.route'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='stoppages',
            field=models.ManyToManyField(blank=True, to='bus_app.stoppage'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_app.route'),
        ),
    ]
