# Generated by Django 5.1.5 on 2025-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0037_allotment_route_allotment_stoppages_alter_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='crm_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
