# Generated by Django 5.1.5 on 2025-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0038_alter_student_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='permit_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='permit_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
