# Generated by Django 5.1.5 on 2025-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0039_bus_permit_bus_permit_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='stoppages',
            field=models.ManyToManyField(to='bus_app.stoppage'),
        ),
    ]
