# Generated by Django 5.1.5 on 2025-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0040_alter_allotment_stoppages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
