# Generated by Django 5.1.5 on 2025-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0041_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
