# Generated by Django 5.1.5 on 2025-02-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0043_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
    ]
