# Generated by Django 5.1.5 on 2025-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_app", "0045_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="fare",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
